version: "3"
services:
  pg:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_PASSWORD: pgpass
    ports:
      - "5432:5432"
  api:
    build: .
    depends_on:
      - pg
    ports:
      - "8000:8000"
